insert
	$p isa person has identifier <pid>
		has firstname <name1>,
		
		if (<surname> != "") do 
		{
		has surname <surname>,
		}

		if (<name2> != "") do 
		{
		has middlename <name2>,
		}

		if (<picture> != "") do 
		{
		has picture <picture>,
		}

		if (<age> != "") do 
		{
		has age @long(<age>),
		}

		if (<born> != "") do 
		{
		has birth-date <born>,
		}

		if (<dead> != "") do 
		{
		has death-date <dead>,
		}

		has gender <gender>;

	
	