insert

# Entities

person sub entity
	plays-role parent
	plays-role child
	plays-role spouse1
	plays-role spouse2

	has-resource identifier
	has-resource firstname
	has-resource surname
	has-resource middlename
	has-resource picture
	has-resource age
	has-resource birth-date
	has-resource death-date
	has-resource gender;

# Resources

identifier sub resource datatype string;
firstname sub resource datatype string;
surname sub resource datatype string;
middlename sub resource datatype string;
picture sub resource datatype string;
age sub resource datatype long;
birth-date sub resource datatype string;
death-date sub resource datatype string;
gender sub resource datatype string;

# Roles and Relations

marriage sub relation
	has-role spouse1
	has-role spouse2
	has-resource picture;

spouse1 sub role;
spouse2 sub role;

parentship sub relation
	has-role parent
	has-role child;

parent sub role;
child sub role;	

# The following is added by the Grakn reasoner

person 
	plays-role wife
	plays-role husband
	plays-role granddaughter
	plays-role grandson
	plays-role father-in-law
	plays-role mother-in-law
	plays-role daughter-in-law
	plays-role son-in-law
	plays-role son
	plays-role daughter
	plays-role sibling1
	plays-role sibling2
	plays-role grandparent
	plays-role grandchild
	plays-role cousin1
	plays-role cousin2
	plays-role child-in-law
	plays-role parent-in-law
	plays-role mother
	plays-role father
	plays-role grandmother
	plays-role grandfather;

marriage sub relation
	has-role husband
	has-role wife;

husband sub role;
wife sub role;

parentship sub relation
	has-role mother
	has-role father
	has-role son
	has-role daughter;

mother sub parent;
father sub parent;
son sub child;
daughter sub child;

siblings sub relation
	has-role sibling1
	has-role sibling2;

sibling sub role is-abstract;
sibling1 sub sibling;
sibling2 sub sibling;

grandparentship sub relation
	has-role grandparent
	has-role grandfather
	has-role grandmother
	has-role grandchild
	has-role granddaughter
	has-role grandson;

grandparent sub role;
grandfather sub grandparent;
grandmother sub grandparent;
grandchild sub role;
grandson sub grandchild;
granddaughter sub grandchild;

cousins sub relation
	has-role cousin1
	has-role cousin2;

cousin sub role is-abstract;
cousin1 sub cousin;
cousin2 sub cousin;

in-laws sub relation
	has-role child-in-law
	has-role son-in-law
	has-role daughter-in-law
	has-role parent-in-law
	has-role mother-in-law
	has-role father-in-law;

child-in-law sub role;
son-in-law sub child-in-law;
daughter-in-law sub child-in-law;
parent-in-law sub role;
mother-in-law sub parent-in-law;
father-in-law sub parent-in-law;