insert
	$p isa person has identifier <pid>;
	$x isa birth has firstname <name1>,
		has gender <gender>,
		has confidence "high";
	(happening: $x, protagonist: $p) isa event-protagonist,
		has function "newborn";
	if (<surname> != "") do 
		{
		$x has surname <surname>;
		}
	if (<name2> != "") do 
		{
		$x has middlename <name2>;
		}
	if (<born> != "") do 
		{
		$x has birth-date <born>;
		}
	$y isa death has confidence "high";
	(happening: $y, protagonist: $p) isa event-protagonist,
			has function "deceased";
	if (<dead> != "") do 
		{
		$y 	has death-date <dead>;
		}

	if (<age> != "") do 
		{
		$y 	has age @long(<age>);
		}