insert $118792 has surname "Newman" has confidence "high" isa birth has gender "female" has firstname "Eliza";
$106504 has confidence "high" has death-date "1898-09-10" isa death has age 87;
$126984 has confidence "high" isa death;
$40976 has surname "Titus" has confidence "high" isa birth has middlename "Ann" has gender "female" has birth-date "1845-09-10" has firstname "Amanda";
$40980576 has firstname "Ron" has surname "Newman" has confidence "high" isa birth has gender "male";
$299024 has surname "Dudley" has confidence "high" isa birth has gender "female" has middlename "Josephine" has firstname "Susan";
$270352 has confidence "high" isa death;
$417808 has death-date "1872-03-06" has age 74 has confidence "high" isa death;
$81969400 has confidence "high" isa death;
$82010360 has confidence "high" isa death;
$82174200 has firstname "Stephen" has surname "Newman" has confidence "high" isa birth has gender "male";
$82223352 has confidence "high" isa death;
$41058392 has birth-date "1811-03-06" has surname "Newman" has confidence "high" isa birth has gender "male" has firstname "Henry";
$40996936 has confidence "high" isa death;
$41070664 has firstname "Catherine" has confidence "high" isa birth has gender "female" has surname "Young" has birth-date "before 1798";
$41091144 has firstname "Margaret" has surname "Newman" has confidence "high" isa birth has gender "female";
$41132104 has firstname "Rosalie" has confidence "high" isa birth has gender "female";
$41201736 has confidence "high" isa death;
$41238600 has confidence "high" isa birth has gender "male" has firstname "Frederick" has surname "Shafner";
$41300040 has firstname "Barbara" has confidence "high" isa birth has gender "female" has surname "Shafner";
$20552 has confidence "high" isa death;
$81961136 has identifier "w07" isa wedding has confidence "high";
$20576 has confidence "high" isa death;
$40996880 has firstname "Barbara" has birth-date "1833-04-08" has confidence "high" isa birth has gender "female" has middlename "Ellen" has surname "Niesz";
$110688 has death-date "1942-04-08" has age 96 has confidence "high" isa death;
$233568 has confidence "high" has age 93 has death-date "1868-03-15" isa death;
$41099280 has confidence "high" isa death;
$41140240 has confidence "high" isa death;
$266336 has age 76 has death-date "1900" has confidence "high" isa death;
$41181200 has confidence "high" isa death;
$381024 has birth-date "1798-04-09" has firstname "Mary" has confidence "high" isa birth has surname "Young" has gender "female";
$41349136 has surname "Newman" has confidence "high" isa birth has gender "male" has birth-date "circa 1803" has firstname "Robert";
$434272 has age 90 has confidence "high" isa death;
$41304080 has confidence "high" isa death;
$512096 has firstname "Mary" has confidence "high" isa birth has gender "female" has surname "Niesz" has birth-date "1824-05-29";
$569440 has confidence "high" isa death;
$610400 has firstname "Jacob" has confidence "high" has birth-date "1825-11-18" isa birth has gender "male" has middlename "J." has surname "Niesz";
$41009176 has firstname "Barbara" has surname "Titus" has confidence "high" isa birth has middlename "Ellen" has gender "female" has birth-date "1850-09-18";
$41058328 has firstname "Barbara" has confidence "high" isa birth has birth-date "1773-06-06" has gender "female" has surname "Herchelroth";
$41029656 has confidence "high" has age 82 isa death has death-date "1933-01-10";
$749664 has confidence "high" isa death;
$860256 has confidence "high" isa death;
$41295896 has confidence "high" has death-date "1891-08" has age 65 isa death;
$41324568 has confidence "high" isa death;
$41185280 has firstname "Catherine" has birth-date "1824-10-20" has confidence "high" isa birth has gender "female" has surname "Niesz";
$41234432 has confidence "high" isa birth has gender "female" has surname "Niesz" has birth-date "1820-08-27" has firstname "Elizabeth";
$41304064 has birth-date "1857-12-24" has firstname "William" has surname "Titus" has confidence "high" isa birth has gender "male" has middlename "Sanford";
$41320448 has death-date "1957-03-28" has confidence "high" has age 99 isa death;
$41402368 has firstname "Mary" has confidence "high" isa birth has surname "Guthrie" has gender "female";
$77944 has identifier "w08" isa wedding has confidence "high";
$98424 has date "1884-10-21" isa wedding has identifier "w04" has confidence "high";
$41517056 has age 91 has confidence "high" has death-date "1913" isa death;
$139384 isa wedding has date "1845-10-21" has confidence "high" has identifier "w01";
$82026648 has identifier "w17" isa wedding has confidence "high";
$41619456 has firstname "Mary" has surname "Titus" has confidence "high" isa birth has gender "female" has middlename "Melissa" has birth-date "1847-08-12";
$41668608 has confidence "high" isa birth has gender "male" has firstname "George" has surname "Niesz";
$282744 isa wedding has identifier "w03" has confidence "high";
$41705472 has birth-date "1774-08-02" has surname "Newman" has confidence "high" has firstname "John" isa birth has gender "male";
$335992 has identifier "w06" has date "1844-11-21" isa wedding has confidence "high";
$82116760 has date "1820-05-23" isa wedding has confidence "high" has identifier "w05";
$82133144 isa wedding has confidence "high" has date "1795 circa" has identifier "w12";
$41783296 has surname "Titus" has confidence "high" has firstname "Timothy" isa birth has gender "male";
$41803776 has firstname "Byron" has confidence "high" has surname "Culbertson" isa birth has gender "male";
$40988912 has identifier "w18" isa wedding has confidence "high";
$41009392 has identifier "w09" isa wedding has confidence "high";
$168064 has confidence "high" isa death;
$41091312 isa wedding has identifier "w13" has confidence "high";
$41107696 isa wedding has identifier "w14" has confidence "high";
$229504 has confidence "high" isa birth has gender "female" has surname "Shafner" has firstname "Elizabeth";
$40988920 has confidence "high" isa death;
$41214200 has firstname "Jacob" has confidence "high" isa birth has gender "male" has surname "Young";
$123031768 isa wedding has identifier "w15" has confidence "high" has date "1829-10-29";
$41324792 has death-date "1946-05-10" has confidence "high" has age 98 isa death;
$41369848 has confidence "high" has death-date "1862-12-26" has age 88 isa death;
$41406712 has confidence "high" isa death;
$73872 has firstname "Andrew" has confidence "high" isa birth has gender "male" has surname "Shafner";
$41009368 has confidence "high" isa death;
$41025752 has surname "Newman" has confidence "high" has firstname "Lucinda" isa birth has gender "female";
$41140440 has surname "Newman" has confidence "high" isa birth has gender "female" has firstname "Amanda";
$41119960 has confidence "high" isa death;
$266408 has death-date "before 1798-10" has confidence "high" isa death;
$377000 has surname "Weaver" has confidence "high" isa birth has gender "female" has firstname "Elizabeth";
$450728 has confidence "high" has birth-date "1798-01-02" has firstname "John" isa birth has gender "male" has surname "Niesz";
$4272 has firstname "Sarah" has surname "Hane" has confidence "high" isa birth has gender "female";
$90288 has surname "Newman" has confidence "high" has firstname "John" isa birth has middlename "L." has gender "male";
$40997056 has firstname "Catherine" has surname "Newman" has confidence "high" isa birth has gender "female";
$41029824 has middlename "E." has firstname "Barbara" has surname "Newman" has confidence "high" isa birth has gender "female";
$41042112 has confidence "high" isa death;
$41054400 has confidence "high" isa death;
$41005232 has surname "Newman" has confidence "high" isa birth has gender "male" has firstname "Peter";
$41054384 has confidence "high" isa death;
$41062576 has age 74 has death-date "1904-03-26" has confidence "high" isa death;
$41111728 has confidence "high" isa death;
$41238704 has firstname "Haman" has surname "Newman" has confidence "high" isa birth has gender "male";
$41291952 has middlename "Kossuth" has confidence "high" has birth-date "1836-11-22" has firstname "John" isa birth has gender "male" has surname "Niesz";
$41312432 has surname "Billings" has confidence "high" has firstname "Maggie" isa birth has gender "female";
$41287856 has confidence "high" isa death;
$24776 has confidence "high" isa birth has gender "female" has firstname "Josephine";
$94408 has confidence "high" has age 82 isa death;
$168136 has age 74 has confidence "high" isa death;
$315592 has confidence "high" isa death;
$336072 has surname "Newman" has confidence "high" isa birth has gender "male" has firstname "Harry";
$385224 has age 78 has confidence "high" isa death;
$41058464 isa wedding has confidence "high" has identifier "w20";
$41103520 has identifier "w19" isa wedding has confidence "high";
$122904704 isa wedding has confidence "high" has identifier "w11";
$122925184 isa wedding has confidence "high" has identifier "w22" has date "1854-05-04";
$123060352 has date "1874-12-09" isa wedding has identifier "w02" has confidence "high";
$123080832 isa wedding has confidence "high" has identifier "w10";
$123113600 isa wedding has confidence "high" has identifier "w21";
$233696 has confidence "high" isa death has age 22;
$40968344 has surname "McGaughey" has confidence "high" isa birth has gender "female" has firstname "Isabelle";
$41033880 has confidence "high" isa death;
$41156760 has confidence "high" has firstname "John" isa birth has gender "male" has surname "Shafner";
$41300120 has confidence "high" isa death;
$41324696 has confidence "high" isa death;
$8432 has confidence "high" isa death;
$41200 has confidence "high" has age 52 isa death;
$41472136 has confidence "high" has age 83 isa death;
$65776 has surname "Newman" has confidence "high" isa birth has gender "male" has birth-date "1804 circa" has firstname "Lawrence";
$41521288 has birth-date "1822-05-28" has firstname "William" has confidence "high" isa birth has gender "male" has surname "Niesz";
$131312 has confidence "high" has firstname "Elam" has surname "Smith" isa birth has gender "male" has middlename "G.";
$192752 has confidence "high" isa death;
$200944 has firstname "Hermione" has surname "Newman" has confidence "high" isa birth has gender "female";
$246000 has confidence "high" has birth-date "1842-11-16" isa birth has gender "male" has firstname "Benjamin" has middlename "Franklin" has surname "Niesz";
$254192 has firstname "Barbara" has surname "Newman" has confidence "high" isa birth has gender "female";
$364784 has confidence "high" isa death;
$114936 has birth-date "1829-09-12" has confidence "high" isa birth has gender "male" has firstname "George" has surname "Niesz" has middlename "W.";
$40980616 has confidence "high" isa birth has firstname "Ann" has gender "female" has surname "Niesz" has middlename "Eliza";
$41005192 has surname "Roush" has confidence "high" isa birth has firstname "Delilah" has gender "female";
$81924120 has date "1832-11-29" isa wedding has identifier "w16" has confidence "high";
$205048 has confidence "high" isa birth has gender "female" has firstname "Elizabeth";
$41103496 has firstname "William" has surname "Titus" has confidence "high" isa birth has gender "male" has birth-date "1818-03-23" has middlename "Sanford";
$41132168 has age 76 has confidence "high" isa death has death-date "1905-01-01";
$82055192 isa wedding has confidence "high" has identifier "w00";
$303352 has confidence "high" isa death;
$385272 has firstname "Sarah" has birth-date "1840-01-19" has confidence "high" isa birth has middlename "Ann" has gender "female" has surname "Niesz";
$41238664 has confidence "high" has firstname "John" has surname "Meyers" isa birth has gender "male";
$381176 has confidence "high" isa death;
$41222280 has death-date "1891-12-08" has confidence "high" isa death has age 71;
$41255048 has confidence "high" isa death;
$41341064 has middlename "S." has confidence "high" isa birth has gender "male" has firstname "Samuel" has surname "Bard";
$41324680 has confidence "high" has death-date "1868-10-28" isa death has age 70;
$28680 (happening: $41009368, protagonist: $20488) isa event-protagonist has function "deceased";
$61448 has function "newborn" isa event-protagonist (happening: $41029824, protagonist: $82018552);
$90120 has function "newborn" isa event-protagonist (happening: $41058392, protagonist: $41062592);
$122888 has function "newborn" isa event-protagonist (happening: $82174200, protagonist: $41082976);
$139272 has function "newborn" isa event-protagonist (happening: $41140440, protagonist: $82202872);
$49168 isa event-protagonist (happening: $110688, protagonist: $69728) has function "deceased";
$57360 (happening: $41009176, protagonist: $41091072) has function "newborn" isa event-protagonist;
$40968288 has function "newborn" (happening: $4272, protagonist: $8296) isa event-protagonist;
$40976480 isa event-protagonist (happening: $20552, protagonist: $8296) has function "deceased";
$163856 (happening: $266336, protagonist: $41173128) isa event-protagonist has function "deceased";
$41058400 (happening: $106504, protagonist: $41062592) isa event-protagonist has function "deceased";
$204816 (happening: $41255048, protagonist: $41107704) isa event-protagonist has function "deceased";
$221200 (happening: $41320448, protagonist: $180392) isa event-protagonist has function "deceased";
$278544 has function "newborn" isa event-protagonist (happening: $41214200, protagonist: $41210104);
$401424 (happening: $41369848, protagonist: $417960) isa event-protagonist has function "deceased";
$426000 (happening: $417808, protagonist: $41705608) isa event-protagonist has function "deceased";
$40992872 has function "parent" (happening: $41238704, protagonist: $364672) isa event-protagonist;
$40996968 has function "parent" (happening: $41185280, protagonist: $41705608) isa event-protagonist;
$81977592 (happening: $81969400, protagonist: $40992864) isa event-protagonist has function "deceased";
$82145528 (happening: $118792, protagonist: $82129144) has function "newborn" isa event-protagonist;
$4136 has function "parent" isa event-protagonist (happening: $118792, protagonist: $4240);
$16424 has function "parent" isa event-protagonist (happening: $41156760, protagonist: $139512);
$61480 has function "parent" isa event-protagonist (happening: $90288, protagonist: $8296);
$40976472 has function "newborn" isa event-protagonist (happening: $40980576, protagonist: $20488);
$41009240 (happening: $41025752, protagonist: $41005144) has function "newborn" isa event-protagonist;
$41111640 (happening: $126984, protagonist: $41082976) isa event-protagonist has function "deceased";
$49208 has function "parent" (happening: $385272, protagonist: $41304200) isa event-protagonist;
$57400 has function "parent" (happening: $41103496, protagonist: $41377816) isa event-protagonist;
$65592 has function "parent" (happening: $450728, protagonist: $41660416) isa event-protagonist;
$106552 has function "parent" (happening: $114936, protagonist: $41705608) isa event-protagonist;
$114744 has function "parent" isa event-protagonist (happening: $41619456, protagonist: $41095304);
$40988744 has function "newborn" isa event-protagonist (happening: $24776, protagonist: $33016);
$41017416 has function "newborn" isa event-protagonist (happening: $41005232, protagonist: $61640);
$41025608 (happening: $41033880, protagonist: $61640) isa event-protagonist has function "deceased";
$41029704 (happening: $94408, protagonist: $61680) isa event-protagonist has function "deceased";
$81928408 has function "parent" (happening: $41156760, protagonist: $41250832) isa event-protagonist;
$81936600 has function "parent" (happening: $41005232, protagonist: $176368) isa event-protagonist;
$41099336 has function "newborn" isa event-protagonist (happening: $41091144, protagonist: $159944);
$41222216 (happening: $254192, protagonist: $41201680) has function "newborn" isa event-protagonist;
$41320520 isa event-protagonist has function "deceased" (happening: $385224, protagonist: $41345200);
$12352 has function "parent" isa event-protagonist (happening: $40976, protagonist: $41197704);
$20544 has function "parent" isa event-protagonist (happening: $254192, protagonist: $364672);
$32832 has function "parent" (happening: $41304064, protagonist: $41197704) isa event-protagonist;
$49216 has function "parent" (happening: $41070664, protagonist: $41210104) isa event-protagonist;
$69696 has function "parent" isa event-protagonist (happening: $41185280, protagonist: $41304200);
$77888 has function "parent" (happening: $40996880, protagonist: $41304200) isa event-protagonist;
$94272 has function "parent" isa event-protagonist (happening: $450728, protagonist: $41304088);
$122944 has function "parent" isa event-protagonist (happening: $114936, protagonist: $41304200);
$40992800 has function "parent" (happening: $610400, protagonist: $41705608) isa event-protagonist;
$41000992 has function "parent" isa event-protagonist (happening: $40996880, protagonist: $41705608);
$41021472 has function "parent" isa event-protagonist (happening: $41521288, protagonist: $41304200);
$41074720 has function "parent" isa event-protagonist (happening: $512096, protagonist: $41304200);
$81973424 has function "spouse" isa event-protagonist (happening: $40988912, protagonist: $139512);
$81981616 has function "spouse" (happening: $40988912, protagonist: $41250832) isa event-protagonist;
$82047152 has function "spouse" isa event-protagonist (happening: $123031768, protagonist: $61680);
$82059440 has function "spouse" isa event-protagonist (happening: $282744, protagonist: $69728);
$90208 has function "newborn" isa event-protagonist (happening: $40976, protagonist: $69728);
$41000976 has function "newborn" isa event-protagonist (happening: $40996880, protagonist: $32992);
$176224 has function "newborn" isa event-protagonist (happening: $41103496, protagonist: $41095304);
$81981568 has function "parent" (happening: $41238704, protagonist: $176368) isa event-protagonist;
$249952 has function "newborn" isa event-protagonist (happening: $41185280, protagonist: $41173128);
$82014336 has function "parent" isa event-protagonist (happening: $41058392, protagonist: $417960);
$82026624 has function "parent" isa event-protagonist (happening: $41234432, protagonist: $41705608);
$323680 has function "newborn" isa event-protagonist (happening: $41238664, protagonist: $41107704);
$41156624 (happening: $41156760, protagonist: $221408) has function "newborn" isa event-protagonist;
$41160720 isa event-protagonist (happening: $233696, protagonist: $221408) has function "deceased";
$41185296 isa event-protagonist (happening: $41181200, protagonist: $41177240) has function "deceased";
$41226256 has function "newborn" isa event-protagonist (happening: $229504, protagonist: $229520);
$41230352 (happening: $41287856, protagonist: $229520) isa event-protagonist has function "deceased";
$397408 (happening: $381024, protagonist: $41304200) has function "newborn" isa event-protagonist;
$413792 (happening: $41324680, protagonist: $41304200) isa event-protagonist has function "deceased";
$41316368 (happening: $381176, protagonist: $352456) isa event-protagonist has function "deceased";
$540768 (happening: $41472136, protagonist: $41222168) isa event-protagonist has function "deceased";
$651360 has function "newborn" isa event-protagonist (happening: $377000, protagonist: $41304088);
$684128 (happening: $41619456, protagonist: $41611400) has function "newborn" isa event-protagonist;
$700512 isa event-protagonist has function "deceased" (happening: $41324792, protagonist: $41611400);
$733280 has function "newborn" isa event-protagonist (happening: $41668608, protagonist: $41660416);
$41099288 (happening: $41234432, protagonist: $41197704) has function "newborn" isa event-protagonist;
$839776 has function "newborn" (happening: $41783296, protagonist: $41377816) isa event-protagonist;
$41205784 (happening: $270352, protagonist: $446560) isa event-protagonist has function "deceased";
$41275416 has function "newborn" isa event-protagonist (happening: $41521288, protagonist: $577632);
$4208 has function "parent" isa event-protagonist (happening: $82174200, protagonist: $61680);
$49264 has function "parent" (happening: $41140440, protagonist: $41062592) isa event-protagonist;
$57456 has function "parent" (happening: $41140440, protagonist: $8296) isa event-protagonist;
$82032 has function "parent" (happening: $41029824, protagonist: $8296) isa event-protagonist;
$40984576 has function "newborn" isa event-protagonist (happening: $40980616, protagonist: $4112);
$41025536 (happening: $41005192, protagonist: $40976632) has function "newborn" isa event-protagonist;
$41037824 isa event-protagonist has function "deceased" (happening: $40988920, protagonist: $40976632);
$41144320 (happening: $41132168, protagonist: $41095304) isa event-protagonist has function "deceased";
$41160704 (happening: $41058328, protagonist: $41070840) has function "newborn" isa event-protagonist;
$41385984 has function "newborn" isa event-protagonist (happening: $41341064, protagonist: $241680);
$8312 has function "spouse" (happening: $81924120, protagonist: $8296) isa event-protagonist;
$20600 has function "spouse" isa event-protagonist (happening: $122925184, protagonist: $577632);
$41439232 (happening: $266408, protagonist: $41210104) isa event-protagonist has function "deceased";
$41459712 has function "newborn" isa event-protagonist (happening: $512096, protagonist: $41222168);
$86136 (happening: $77944, protagonist: $118984) has function "spouse" isa event-protagonist;
$123000 has function "spouse" isa event-protagonist (happening: $41009392, protagonist: $319736);
$40964104 has function "parent" isa event-protagonist (happening: $82174200, protagonist: $4240);
$40980488 has function "parent" (happening: $40980576, protagonist: $61680) isa event-protagonist;
$40996872 has function "parent" (happening: $73872, protagonist: $139512) isa event-protagonist;
$41000968 has function "parent" isa event-protagonist (happening: $73872, protagonist: $41250832);
$41009160 has function "parent" isa event-protagonist (happening: $41025752, protagonist: $61680);
$184440 has function "spouse" (happening: $123060352, protagonist: $41107704) isa event-protagonist;
$41558016 isa event-protagonist has function "deceased" (happening: $41295896, protagonist: $340136);
$41611264 isa event-protagonist (happening: $41324568, protagonist: $41304088) has function "deceased";
$81973400 has function "spouse" isa event-protagonist (happening: $77944, protagonist: $33016);
$82006168 has function "spouse" isa event-protagonist (happening: $41009392, protagonist: $41308312);
$82047128 has function "spouse" isa event-protagonist (happening: $123080832, protagonist: $135312);
$41684992 (happening: $749664, protagonist: $41660416) isa event-protagonist has function "deceased";
$82055320 has function "spouse" isa event-protagonist (happening: $41058464, protagonist: $352456);
$82063512 has function "spouse" isa event-protagonist (happening: $123113600, protagonist: $40992864);
$82108568 (happening: $335992, protagonist: $577632) has function "spouse" isa event-protagonist;
$348280 (happening: $335992, protagonist: $40976632) has function "spouse" isa event-protagonist;
$41758720 has function "newborn" isa event-protagonist (happening: $450728, protagonist: $41705608);
$41799680 (happening: $860256, protagonist: $41377816) isa event-protagonist has function "deceased";
$41816064 has function "newborn" isa event-protagonist (happening: $41803776, protagonist: $41398520);
$8320 has function "newborn" isa event-protagonist (happening: $40968344, protagonist: $4240);
$82048 (happening: $114936, protagonist: $118984) has function "newborn" isa event-protagonist;
$41050352 has function "spouse" (happening: $123080832, protagonist: $41345200) isa event-protagonist;
$41066736 has function "spouse" (happening: $82055192, protagonist: $446560) isa event-protagonist;
$41136368 (happening: $82133144, protagonist: $41210104) has function "spouse" isa event-protagonist;
$295040 isa event-protagonist has function "deceased" (happening: $41300120, protagonist: $41250832);
$303232 has function "newborn" (happening: $41312432, protagonist: $41308312) isa event-protagonist;
$40968440 isa event-protagonist (happening: $20576, protagonist: $4112) has function "deceased";
$41042168 (happening: $41029656, protagonist: $41091072) isa event-protagonist has function "deceased";
$41140472 (happening: $41304064, protagonist: $180392) has function "newborn" isa event-protagonist;
$41193720 isa event-protagonist (happening: $434272, protagonist: $241680) has function "deceased";
$41267448 (happening: $41517056, protagonist: $577632) isa event-protagonist has function "deceased";
$41353464 has function "newborn" isa event-protagonist (happening: $41705472, protagonist: $417960);
$40988896 has function "parent" (happening: $41070664, protagonist: $41070840) isa event-protagonist;
$143504 isa event-protagonist (happening: $168136, protagonist: $159944) has function "deceased";
$168080 isa event-protagonist (happening: $41140240, protagonist: $41140376) has function "deceased";
$176272 has function "newborn" isa event-protagonist (happening: $41132104, protagonist: $41177264);
$192656 has function "newborn" isa event-protagonist (happening: $41238704, protagonist: $41177240);
$41033952 has function "parent" isa event-protagonist (happening: $41103496, protagonist: $446560);
$41058528 has function "parent" (happening: $41009176, protagonist: $41197704) isa event-protagonist;
$286864 (happening: $41304080, protagonist: $340192) isa event-protagonist has function "deceased";
$45216 has function "parent" isa event-protagonist (happening: $41300040, protagonist: $41250832);
$81924168 has function "parent" isa event-protagonist (happening: $41349136, protagonist: $417960);
$81936456 has function "parent" isa event-protagonist (happening: $41304064, protagonist: $41095304);
$81956936 has function "parent" isa event-protagonist (happening: $246000, protagonist: $41304200);
$81965128 has function "parent" (happening: $610400, protagonist: $41304200) isa event-protagonist;
$81985608 has function "parent" (happening: $41521288, protagonist: $41705608) isa event-protagonist;
$82047048 has function "parent" isa event-protagonist (happening: $512096, protagonist: $41705608);
$323752 isa event-protagonist (happening: $569440, protagonist: $307368) has function "deceased";
$86192 (happening: $41042112, protagonist: $82018552) isa event-protagonist has function "deceased";
$127152 isa event-protagonist (happening: $41119960, protagonist: $82129144) has function "deceased";
$41017536 (happening: $40997056, protagonist: $40992864) has function "newborn" isa event-protagonist;
$172208 (happening: $82223352, protagonist: $82202872) isa event-protagonist has function "deceased";
$41025728 isa event-protagonist has function "deceased" (happening: $82010360, protagonist: $41005144);
$41046208 has function "newborn" isa event-protagonist (happening: $90288, protagonist: $41033824);
$41058496 isa event-protagonist (happening: $41054400, protagonist: $41033824) has function "deceased";
$8376 has function "parent" (happening: $41349136, protagonist: $41070840) isa event-protagonist;
$12472 has function "parent" isa event-protagonist (happening: $40976, protagonist: $41095304);
$20664 has function "parent" isa event-protagonist (happening: $254192, protagonist: $176368);
$45240 has function "parent" isa event-protagonist (happening: $246000, protagonist: $41705608);
$90296 has function "parent" (happening: $65776, protagonist: $41070840) isa event-protagonist;
$114872 has function "parent" isa event-protagonist (happening: $41091144, protagonist: $364672);
$127160 has function "parent" (happening: $381024, protagonist: $41210104) isa event-protagonist;
$139448 has function "parent" (happening: $41009176, protagonist: $41095304) isa event-protagonist;
$41066672 isa event-protagonist (happening: $41062576, protagonist: $118984) has function "deceased";
$41078960 (happening: $41070664, protagonist: $139512) has function "newborn" isa event-protagonist;
$81940512 has function "parent" (happening: $40997056, protagonist: $8296) isa event-protagonist;
$81981472 has function "parent" isa event-protagonist (happening: $200944, protagonist: $61680);
$81989664 has function "parent" isa event-protagonist (happening: $200944, protagonist: $4240);
$82010144 has function "parent" isa event-protagonist (happening: $229504, protagonist: $41250832);
$41271472 (happening: $303352, protagonist: $41201680) isa event-protagonist has function "deceased";
$41324720 has function "newborn" isa event-protagonist (happening: $336072, protagonist: $340192);
$41373872 isa event-protagonist (happening: $364784, protagonist: $364672) has function "deceased";
$86216 has function "newborn" (happening: $65776, protagonist: $61680) isa event-protagonist;
$262344 has function "newborn" (happening: $246000, protagonist: $250056) isa event-protagonist;
$311496 has function "newborn" isa event-protagonist (happening: $41291952, protagonist: $319736);
$40972448 (happening: $122904704, protagonist: $250056) has function "spouse" isa event-protagonist;
$41029792 (happening: $139384, protagonist: $41197704) has function "spouse" isa event-protagonist;
$41042080 has function "spouse" (happening: $82026648, protagonist: $82202872) isa event-protagonist;
$41070752 has function "spouse" isa event-protagonist (happening: $123113600, protagonist: $41177240);
$41111712 (happening: $41091312, protagonist: $417960) has function "spouse" isa event-protagonist;
$41140384 (happening: $41107696, protagonist: $364672) has function "spouse" isa event-protagonist;
$41156768 has function "spouse" (happening: $82133144, protagonist: $41070840) isa event-protagonist;
$41001128 has function "parent" isa event-protagonist (happening: $229504, protagonist: $139512);
$28896 (happening: $40996936, protagonist: $33016) isa event-protagonist has function "deceased";
$40980624 has function "parent" isa event-protagonist (happening: $40997056, protagonist: $41062592);
$41005200 has function "parent" (happening: $40980576, protagonist: $4240) isa event-protagonist;
$164064 has function "newborn" isa event-protagonist (happening: $131312, protagonist: $135312);
$188640 isa event-protagonist has function "deceased" (happening: $192752, protagonist: $176368);
$41042064 has function "parent" (happening: $90288, protagonist: $41062592) isa event-protagonist;
$196832 has function "newborn" isa event-protagonist (happening: $200944, protagonist: $41140376);
$217312 isa event-protagonist (happening: $168064, protagonist: $41177264) has function "deceased";
$336096 (happening: $41324696, protagonist: $41308312) isa event-protagonist has function "deceased";
$12520 has function "parent" isa event-protagonist (happening: $336072, protagonist: $364672);
$73960 has function "parent" isa event-protagonist (happening: $41291952, protagonist: $41304200);
$78056 has function "parent" (happening: $41058392, protagonist: $41070840) isa event-protagonist;
$82152 has function "parent" isa event-protagonist (happening: $41091144, protagonist: $176368);
$90344 has function "parent" isa event-protagonist (happening: $41234432, protagonist: $41304200);
$40976536 isa event-protagonist has function "deceased" (happening: $8432, protagonist: $4240);
$41017496 (happening: $41200, protagonist: $32992) isa event-protagonist has function "deceased";
$41066648 (happening: $73872, protagonist: $69776) has function "newborn" isa event-protagonist;
$41218200 (happening: $41201736, protagonist: $250056) isa event-protagonist has function "deceased";
$94448 (happening: $41054384, protagonist: $69776) isa event-protagonist has function "deceased";
$127216 isa event-protagonist (happening: $41099280, protagonist: $139512) has function "deceased";
$40980608 has function "parent" (happening: $41005232, protagonist: $364672) isa event-protagonist;
$41013376 has function "parent" isa event-protagonist (happening: $41025752, protagonist: $4240);
$41500808 has function "newborn" isa event-protagonist (happening: $299024, protagonist: $307368);
$41025664 has function "parent" (happening: $41300040, protagonist: $139512) isa event-protagonist;
$41582728 has function "newborn" isa event-protagonist (happening: $610400, protagonist: $340136);
$81944592 has function "parent" isa event-protagonist (happening: $336072, protagonist: $176368);
$81969168 has function "parent" (happening: $385272, protagonist: $41705608) isa event-protagonist;
$81973264 has function "parent" (happening: $65776, protagonist: $417960) isa event-protagonist;
$81977360 has function "parent" (happening: $41291952, protagonist: $41705608) isa event-protagonist;
$82006032 has function "parent" isa event-protagonist (happening: $381024, protagonist: $41070840);
$82022416 has function "parent" (happening: $41619456, protagonist: $41197704) isa event-protagonist;
$286960 has function "newborn" isa event-protagonist (happening: $41238600, protagonist: $41250832);
$332016 has function "newborn" isa event-protagonist (happening: $41300040, protagonist: $352456);
$348400 has function "newborn" (happening: $41349136, protagonist: $364672) isa event-protagonist;
$41840776 (happening: $41406712, protagonist: $41398520) isa event-protagonist has function "deceased";
$184568 (happening: $41111728, protagonist: $135312) isa event-protagonist has function "deceased";
$81932312 has function "spouse" isa event-protagonist (happening: $81924120, protagonist: $41062592);
$81960984 (happening: $81961136, protagonist: $41222168) has function "spouse" isa event-protagonist;
$81965080 has function "spouse" isa event-protagonist (happening: $81961136, protagonist: $241680);
$217336 (happening: $205048, protagonist: $176368) has function "newborn" isa event-protagonist;
$82018328 has function "spouse" (happening: $123060352, protagonist: $41091072) isa event-protagonist;
$41164936 isa event-protagonist has function "deceased" (happening: $233568, protagonist: $41070840);
$82092056 (happening: $282744, protagonist: $41398520) has function "spouse" isa event-protagonist;
$82096152 has function "spouse" isa event-protagonist (happening: $41103520, protagonist: $41173128);
$82104344 (happening: $41103520, protagonist: $221408) has function "spouse" isa event-protagonist;
$336120 (happening: $315592, protagonist: $319736) isa event-protagonist has function "deceased";
$41226376 isa event-protagonist has function "deceased" (happening: $41222280, protagonist: $41197704);
$82124824 has function "spouse" isa event-protagonist (happening: $41107696, protagonist: $176368);
$82128920 has function "spouse" (happening: $82116760, protagonist: $41705608) isa event-protagonist;
$393464 (happening: $385272, protagonist: $41345200) has function "newborn" isa event-protagonist;
$41402504 (happening: $41402368, protagonist: $446560) has function "newborn" isa event-protagonist;
$122888264 has function "parent" (happening: $118792, protagonist: $61680) isa event-protagonist;
$122904648 has function "parent" isa event-protagonist (happening: $41029824, protagonist: $41062592);
$122912984 has function "spouse" isa event-protagonist (happening: $122925184, protagonist: $4112);
$123011288 has function "spouse" isa event-protagonist (happening: $41058464, protagonist: $340136);
$123039960 has function "spouse" (happening: $123031768, protagonist: $4240) isa event-protagonist;
$122921088 (happening: $122904704, protagonist: $41177264) has function "spouse" isa event-protagonist;
$122994816 has function "spouse" isa event-protagonist (happening: $98424, protagonist: $180392);
$123007104 has function "spouse" isa event-protagonist (happening: $98424, protagonist: $307368);
$123039872 has function "spouse" (happening: $139384, protagonist: $41095304) isa event-protagonist;
$123052160 has function "spouse" isa event-protagonist (happening: $82026648, protagonist: $61640);
$123146368 has function "spouse" isa event-protagonist (happening: $82055192, protagonist: $41377816);
$123195520 has function "spouse" isa event-protagonist (happening: $41091312, protagonist: $41070840);
$123265152 (happening: $82116760, protagonist: $41304200) has function "spouse" isa event-protagonist;
$4144 isa conclusion-evidence (conclusion: $122925184, evidence: $81956872);
$16432 isa conclusion-evidence (conclusion: $122925184, evidence: $163852504);
$163844224 isa conclusion-evidence (conclusion: $41185280, evidence: $81948840);
$40964136 isa conclusion-evidence (conclusion: $82116760, evidence: $163844312);
$122884120 isa conclusion-evidence (conclusion: $122925184, evidence: $81924264);
$122888440 isa conclusion-evidence (conclusion: $266336, evidence: $81948840);
$364672 isa person has identifier "Robert Newman";
$20488 isa person has identifier "Ron Newman";
$40976632 isa person has identifier "Delilah Roush";
$41070840 isa person has identifier "Barbara Herchelroth";
$41107704 has identifier "John Meyers" isa person;
$41210104 isa person has identifier "Jacob Young";
$41398520 isa person has identifier "Byron Culbertson";
$4112 isa person has identifier "Ann Eliza Niesz";
$4240 isa person has identifier "Isabelle McGaughey";
$69776 isa person has identifier "Andrew Shafner";
$40992864 isa person has identifier "Catherine Newman";
$135312 isa person has identifier "Elam G. Smith";
$41033824 isa person has identifier "John L. Newman";
$41082976 has identifier "Stephen Newman" isa person;
$229520 isa person has identifier "Elizabeth Shafner";
$241680 isa person has identifier "Samuel S. Bard";
$82018552 has identifier "Barbara E. Newman" isa person;
$82129144 has identifier "Eliza Newman" isa person;
$82202872 has identifier "Amanda Newman" isa person;
$41005144 isa person has identifier "Lucinda Newman";
$180392 isa person has identifier "William Sanford Titus Jr.";
$307368 isa person has identifier "Susan Josephine Dudley";
$340136 isa person has identifier "Jacob J. Niesz";
$417960 has identifier "John Newman" isa person;
$41062592 isa person has identifier "Henry Newman";
$41177264 isa person has identifier "Rosalie";
$41345200 isa person has identifier "Sarah Ann Niesz";
$61640 isa person has identifier "Peter Newman";
$118984 isa person has identifier "George W. Niesz";
$159944 isa person has identifier "Margaret Newman";
$250056 isa person has identifier "Benjamin Franklin Niesz";
$352456 isa person has identifier "Barbara Shafner";
$32992 isa person has identifier "Barbara Ellen Niesz";
$69728 isa person has identifier "Amanda Ann Titus";
$221408 isa person has identifier "John Shafner";
$41201680 isa person has identifier "Barbara Newman";
$340192 isa person has identifier "Harry Newman";
$41250832 isa person has identifier "Frederick Shafner";
$446560 isa person has identifier "Mary Guthrie";
$8296 has identifier "Sarah Hane" isa person;
$577632 has identifier "William Niesz" isa person;
$41140376 has identifier "Hermione Newman" isa person;
$41177240 has identifier "Haman Newman" isa person;
$41222168 isa person has identifier "Mary Niesz";
$41304088 has identifier "Elizabeth Weaver" isa person;
$41308312 isa person has identifier "Maggie Billings";
$41377816 isa person has identifier "Timothy Titus";
$61680 isa person has identifier "Lawrence Newman";
$176368 isa person has identifier "Elizabeth";
$41611400 isa person has identifier "Mary Melissa Titus";
$41091072 isa person has identifier "Barbara Ellen Titus";
$41705608 has identifier "John Niesz" isa person;
$33016 isa person has identifier "Josephine";
$139512 isa person has identifier "Catherine Young";
$41095304 has identifier "William Sanford Titus" isa person;
$41660416 has identifier "George Niesz" isa person;
$319736 isa person has identifier "John Kossuth Niesz";
$41173128 isa person has identifier "Catherine Niesz";
$41197704 isa person has identifier "Elizabeth Niesz";
$41304200 has identifier "Mary Young" isa person;
$81924264 has document-location "http:\/\/2.bp.blogspot.com\/-AT7bLradHgU\/TsfF8VuBpaI\/AAAAAAAAADA\/uodQOYjQikE\/s1600\/willsusieanothercouplesm.jpg" has document-type "picture" has identifier "d03" isa document has notes "Couple Picture";
$81948840 has document-type "picture" has identifier "d01" has notes "Dated Picture of Catherine Niesz" has document-location "http:\/\/www.christliebfamilyassociation.com\/images\/CatherineNieszChristlieb.jpg" isa document;
$81956872 has document-type "picture" has identifier "d04" has document-location "http:\/\/1.bp.blogspot.com\/-55rq7E-zyDs\/UxS_Khn5OUI\/AAAAAAAAATI\/8Ls-XKmCUSc\/s1600\/willsusie.jpg" isa document has notes "Couple Picture";
$163844312 has document-type "picture" has identifier "d02" has document-location "http:\/\/1.bp.blogspot.com\/-Ty9Ox8v7LUw\/VKoGzIlsMII\/AAAAAAAAAZw\/UtkUvrujvBQ\/s1600\/johnandmary.jpg" isa document has notes "Actual Picture of John Niesz and Mary Young";
$163852504 has document-type "wedding certificate" has notes "Wedding Certificate of William and Ann Eliza Niesz" isa document has identifier "d05" has document-location "http:\/\/1.bp.blogspot.com\/-psKyDN-C4Wk\/UtmV8j-hKpI\/AAAAAAAAAQ0\/A9SScr0C3Jo\/s1600\/1860jancontractsm.jpg";
