insert

platform sub entity
	has-resource platform-name
	plays-role supports;
	
platform-name sub resource datatype string;
supports sub role;
runs-on sub role;

genre sub entity
	has-resource genre-name
	plays-role genre-of-game;
	
genre-name sub resource datatype string;
game-with-genre sub role;
genre-of-game sub role;

game sub entity
	has-resource title
	has-resource score
	has-resource score-phrase
	has-resource release-year
	plays-role game-with-genre
	plays-role runs-on;
	
title sub resource datatype string;
score sub resource datatype double;
score-phrase sub resource datatype string;
release-year sub resource datatype string;

compatibility sub relation
	has-role supports
	has-role runs-on;

has-genre sub relation
	has-role game-with-genre
	has-role genre-of-game;


