match
	$genre has genre-name <genre>; 
	$platform has platform-name <platform>;
	
insert $x isa game 
	has title <title>
	has score-phrase <score_phrase>
	has score @double(<score>)
	has release-year <release_year>;
	(game-with-genre: $x, genre-of-game: $genre) isa has-genre;
	(supports: $platform, runs-on: $x) isa compatibility;