insert

pet sub entity
    has-resource name
    has-resource sex
    has-resource birth
    has-resource death
    plays-role owned
    is-abstract;

cat sub pet;
dog sub pet;
snake sub pet;
hamster sub pet;
bird sub pet;

person sub entity
    has-resource name
    has-resource email
    plays-role owner;

owns sub relation
    has-role owner
    has-role owned;

owner sub role;
owned sub role;

email sub resource datatype string;
name sub resource datatype string;
sex sub resource datatype string;
birth sub resource datatype string;
death sub resource datatype string;

