$4304 isa cyl value 8;
$40968344 isa cyl value 4;
$41029800 isa cyl value 6;
$41037912 isa cyl value 8;
$188488 isa cyl value 4;
$41422856 isa hp value 230;
$41032 isa hp value 180;
$41336984 value 97 isa hp;
$614472 isa hp value 105;
$303208 value 65 isa hp;
$41296040 isa hp value 52;
$41095192 isa hp value 150;
$41099264 value 95 isa hp;
$61544 value 335 isa hp;
$41029784 value 62 isa hp;
$41152512 value 66 isa hp;
$41152600 value 110 isa hp;
$41001112 value 109 isa hp;
$41123928 value 93 isa hp;
$40964096 value 91 isa hp;
$40972288 value 205 isa hp;
$401616 isa hp value 215;
$41074840 isa hp value 264;
$151624 value 175 isa hp;
$41078952 value 113 isa hp;
$41181352 value 123 isa hp;
$41238680 isa hp value 245;
$159952 (made: $41115656, maker: $4216) isa manufactured;
$41209944 isa manufactured (made: $41209856, maker: $37032);
$294984 (made: $41050280, maker: $4184) isa manufactured;
$299080 isa manufactured (made: $41058328, maker: $69680);
$41283736 (made: $41250840, maker: $4184) isa manufactured;
$41242792 (made: $41291784, maker: $8280) isa manufactured;
$41381888 isa manufactured (made: $766024, maker: $41048);
$41197656 (made: $204904, maker: $4184) isa manufactured;
$41209880 (made: $561224, maker: $8280) isa manufactured;
$41394184 (made: $41369608, maker: $28760) isa manufactured;
$41074688 (made: $49256, maker: $4184) isa manufactured;
$41259176 isa manufactured (made: $41271320, maker: $12336);
$41025536 isa manufactured (made: $41013400, maker: $40964128);
$147664 (made: $127184, maker: $20608) isa manufactured;
$712776 (made: $41259096, maker: $24664) isa manufactured;
$41406472 (made: $41385984, maker: $12336) isa manufactured;
$41275560 (made: $340176, maker: $20648) isa manufactured;
$41185280 isa manufactured (made: $41132184, maker: $12464);
$40992936 (made: $12496, maker: $49200) isa manufactured;
$41005064 (made: $40964248, maker: $4184) isa manufactured;
$41168 (made: $28880, maker: $40968224) isa manufactured;
$413768 (made: $41132040, maker: $24664) isa manufactured;
$237640 (made: $41033728, maker: $16552) isa manufactured;
$41341016 (made: $41373848, maker: $69680) isa manufactured;
$41009304 isa manufactured (made: $41000960, maker: $32936);
$41287688 (made: $282832, maker: $8280) isa manufactured;
$557128 (made: $41214040, maker: $4184) isa manufactured;
$41103512 isa manufactured (made: $41111552, maker: $12336);
$41148440 (made: $159848, maker: $4184) isa manufactured;
$41349288 (made: $806984, maker: $28760) isa manufactured;
$41365672 (made: $41353384, maker: $8280) isa manufactured;
$479304 isa manufactured (made: $41168984, maker: $12464);
$127184 has model "Lotus Europa" has mpg 30.4 has carb 2 isa manual-car has hp 113 has disp 95.1 has wt 1.513 has gear 5 has cyl 4;
$41385984 has gear 3 has wt 3.215 has disp 258.0 has carb 1 isa automatic-car has model "Hornet 4 Drive" has mpg 21.4 has hp 110 has cyl 6;
$561224 has wt 3.57 has gear 3 has model "Duster 360" has hp 245 has disp 360.0 isa automatic-car has cyl 8 has mpg 14.3 has carb 4;
$41050280 has disp 140.8 has wt 3.15 has carb 2 has mpg 22.8 isa automatic-car has model "Merc 230" has gear 4 has cyl 4 has hp 95;
$204904 has model "Merc 450SE" has gear 3 has carb 3 has hp 180 has wt 4.07 isa automatic-car has cyl 8 has mpg 16.4 has disp 275.8;
$41132184 isa manual-car has model "Mazda RX4 Wag" has mpg 21.0 has wt 2.875 has disp 160.0 has carb 4 has gear 4 has hp 110 has cyl 6;
$41132040 has disp 79.0 has wt 1.935 isa manual-car has carb 1 has mpg 27.3 has hp 66 has gear 4 has cyl 4 has model "Fiat X1-9";
$41259096 isa manual-car has carb 1 has model "Fiat 128" has wt 2.2 has disp 78.7 has hp 66 has gear 4 has cyl 4 has mpg 32.4;
$282832 has mpg 15.5 has gear 3 has carb 2 has hp 150 has disp 318.0 isa automatic-car has cyl 8 has model "Dodge Challenger" has wt 3.52;
$49256 has mpg 24.4 has carb 2 isa automatic-car has model "Merc 240D" has gear 4 has disp 146.7 has cyl 4 has hp 62 has wt 3.19;
$12496 has disp 120.3 has hp 91 has carb 2 isa manual-car has mpg 26.0 has wt 2.14 has gear 5 has cyl 4 has model "Porsche 914-2";
$41271320 has gear 3 has carb 2 has disp 360.0 isa automatic-car has cyl 8 has model "Hornet Sportabout" has mpg 18.7 has wt 3.44 has hp 175;
$41013400 has wt 2.77 isa manual-car has carb 6 has mpg 19.7 has disp 145.0 has gear 5 has hp 175 has model "Ferrari Dino" has cyl 6;
$41214040 has model "Merc 280" has hp 123 isa automatic-car has carb 4 has mpg 19.2 has gear 4 has wt 3.44 has disp 167.6 has cyl 6;
$41168984 isa manual-car has mpg 21.0 has model "Mazda RX4" has disp 160.0 has carb 4 has wt 2.62 has gear 4 has hp 110 has cyl 6;
$41353384 has disp 440.0 has gear 3 has hp 230 has mpg 14.7 isa automatic-car has model "Chrysler Imperial" has cyl 8 has carb 4 has wt 5.345;
$159848 has mpg 17.3 has gear 3 has carb 3 has wt 3.73 has hp 180 isa automatic-car has model "Merc 450SL" has cyl 8 has disp 275.8;
$41209856 has disp 400.0 has gear 3 has carb 2 has wt 3.845 isa automatic-car has cyl 8 has mpg 19.2 has hp 175 has model "Pontiac Firebird";
$40964248 has gear 3 has mpg 15.2 has carb 3 has hp 180 isa automatic-car has wt 3.78 has cyl 8 has disp 275.8 has model "Merc 450SLC";
$41250840 has mpg 17.8 has hp 123 has model "Merc 280C" isa automatic-car has carb 4 has gear 4 has wt 3.44 has disp 167.6 has cyl 6;
$41115656 has disp 108.0 has wt 2.32 has model "Datsun 710" isa manual-car has carb 1 has mpg 22.8 has hp 93 has gear 4 has cyl 4;
$41111552 has model "AMC Javelin" has gear 3 has wt 3.435 has mpg 15.2 has carb 2 has hp 150 isa automatic-car has cyl 8 has disp 304.0;
$41369608 has mpg 33.9 has model "Toyota Corolla" has wt 1.835 isa manual-car has carb 1 has hp 65 has disp 71.1 has gear 4 has cyl 4;
$28880 has gear 3 has mpg 10.4 has model "Cadillac Fleetwood" isa automatic-car has cyl 8 has carb 4 has hp 205 has disp 472.0 has wt 5.25;
$41000960 has wt 2.78 has disp 121.0 has carb 2 isa manual-car has gear 4 has hp 109 has model "Volvo 142E" has cyl 4 has mpg 21.4;
$766024 has disp 75.7 has wt 1.615 has mpg 30.4 has hp 52 has carb 2 isa manual-car has model "Honda Civic" has gear 4 has cyl 4;
$41033728 has mpg 15.0 has wt 3.57 has model "Maserati Bora" isa manual-car has disp 301.0 has cyl 8 has gear 5 has hp 335 has carb 8;
$806984 has gear 3 has disp 120.1 has wt 2.465 has carb 1 isa automatic-car has hp 97 has model "Toyota Corona" has mpg 21.5 has cyl 4;
$340176 has wt 3.84 has disp 350.0 has model "Camaro Z28" has gear 3 has hp 245 isa automatic-car has cyl 8 has carb 4 has mpg 13.3;
$41291784 has hp 105 has gear 3 has model "Valiant" has mpg 18.1 has carb 1 has disp 225.0 isa automatic-car has wt 3.46 has cyl 6;
$41373848 has gear 3 has mpg 10.4 has hp 215 isa automatic-car has cyl 8 has model "Lincoln Continental" has disp 460.0 has carb 4 has wt 5.424;
$41058328 has hp 264 isa manual-car has disp 351.0 has mpg 15.8 has cyl 8 has carb 4 has model "Ford Pantera L" has gear 5 has wt 3.17;
$37032 has maker-name "Pontiac" isa american-maker;
$8280 isa american-maker has maker-name "Chrysler";
$69680 has maker-name "Ford" isa american-maker;
$40968224 has maker-name "Cadillac" isa american-maker;
$20648 has maker-name "Chevrolet" isa american-maker;
$12336 isa american-maker has maker-name "AMC";
$41070760 isa carb value 4;
$41041944 isa carb value 8;
$94280 isa carb value 4;
$40980488 isa carb value 2;
$40964264 isa carb value 3;
$368712 isa carb value 1;
$41156608 isa carb value 1;
$41029640 isa carb value 6;
$41062408 isa carb value 2;
$41197736 value 14.3 isa mpg;
$41205768 value 19.2 isa mpg;
$41119744 value 30.4 isa mpg;
$41144328 value 21.0 isa mpg;
$41127944 value 27.3 isa mpg;
$65744 value 19.7 isa mpg;
$28776 value 21.4 isa mpg;
$41197576 value 16.4 isa mpg;
$41242624 value 15.5 isa mpg;
$254024 value 15.8 isa mpg;
$81992 value 10.4 isa mpg;
$41177096 value 17.3 isa mpg;
$733256 value 13.3 isa mpg;
$327888 value 32.4 isa mpg;
$843848 value 14.7 isa mpg;
$41062552 value 22.8 isa mpg;
$40964104 value 15.2 isa mpg;
$40964120 isa mpg value 26.0;
$262248 value 18.7 isa mpg;
$831560 value 21.5 isa mpg;
$41021464 value 15.0 isa mpg;
$295120 value 18.1 isa mpg;
$41324568 value 33.9 isa mpg;
$41275392 value 17.8 isa mpg;
$192584 value 24.4 isa mpg;
$8264 value 3 isa gear;
$41017352 value 4 isa gear;
$4200 value 5 isa gear;
$41017368 value 4 isa gear;
$127184 has model "Lotus Europa" has mpg 30.4 has carb 2 isa manual-car has hp 113 has disp 95.1 has wt 1.513 has gear 5 has cyl 4;
$41168984 isa manual-car has mpg 21.0 has model "Mazda RX4" has disp 160.0 has carb 4 has wt 2.62 has gear 4 has hp 110 has cyl 6;
$41115656 has disp 108.0 has wt 2.32 has model "Datsun 710" isa manual-car has carb 1 has mpg 22.8 has hp 93 has gear 4 has cyl 4;
$41132184 isa manual-car has model "Mazda RX4 Wag" has mpg 21.0 has wt 2.875 has disp 160.0 has carb 4 has gear 4 has hp 110 has cyl 6;
$41132040 has disp 79.0 has wt 1.935 isa manual-car has carb 1 has mpg 27.3 has hp 66 has gear 4 has cyl 4 has model "Fiat X1-9";
$41369608 has mpg 33.9 has model "Toyota Corolla" has wt 1.835 isa manual-car has carb 1 has hp 65 has disp 71.1 has gear 4 has cyl 4;
$41000960 has wt 2.78 has disp 121.0 has carb 2 isa manual-car has gear 4 has hp 109 has model "Volvo 142E" has cyl 4 has mpg 21.4;
$41259096 isa manual-car has carb 1 has model "Fiat 128" has wt 2.2 has disp 78.7 has hp 66 has gear 4 has cyl 4 has mpg 32.4;
$766024 has disp 75.7 has wt 1.615 has mpg 30.4 has hp 52 has carb 2 isa manual-car has model "Honda Civic" has gear 4 has cyl 4;
$41033728 has mpg 15.0 has wt 3.57 has model "Maserati Bora" isa manual-car has disp 301.0 has cyl 8 has gear 5 has hp 335 has carb 8;
$12496 has disp 120.3 has hp 91 has carb 2 isa manual-car has mpg 26.0 has wt 2.14 has gear 5 has cyl 4 has model "Porsche 914-2";
$41013400 has wt 2.77 isa manual-car has carb 6 has mpg 19.7 has disp 145.0 has gear 5 has hp 175 has model "Ferrari Dino" has cyl 6;
$41058328 has hp 264 isa manual-car has disp 351.0 has mpg 15.8 has cyl 8 has carb 4 has model "Ford Pantera L" has gear 5 has wt 3.17;
$41385984 has gear 3 has wt 3.215 has disp 258.0 has carb 1 isa automatic-car has model "Hornet 4 Drive" has mpg 21.4 has hp 110 has cyl 6;
$41353384 has disp 440.0 has gear 3 has hp 230 has mpg 14.7 isa automatic-car has model "Chrysler Imperial" has cyl 8 has carb 4 has wt 5.345;
$159848 has mpg 17.3 has gear 3 has carb 3 has wt 3.73 has hp 180 isa automatic-car has model "Merc 450SL" has cyl 8 has disp 275.8;
$561224 has wt 3.57 has gear 3 has model "Duster 360" has hp 245 has disp 360.0 isa automatic-car has cyl 8 has mpg 14.3 has carb 4;
$41050280 has disp 140.8 has wt 3.15 has carb 2 has mpg 22.8 isa automatic-car has model "Merc 230" has gear 4 has cyl 4 has hp 95;
$41209856 has disp 400.0 has gear 3 has carb 2 has wt 3.845 isa automatic-car has cyl 8 has mpg 19.2 has hp 175 has model "Pontiac Firebird";
$40964248 has gear 3 has mpg 15.2 has carb 3 has hp 180 isa automatic-car has wt 3.78 has cyl 8 has disp 275.8 has model "Merc 450SLC";
$41250840 has mpg 17.8 has hp 123 has model "Merc 280C" isa automatic-car has carb 4 has gear 4 has wt 3.44 has disp 167.6 has cyl 6;
$204904 has model "Merc 450SE" has gear 3 has carb 3 has hp 180 has wt 4.07 isa automatic-car has cyl 8 has mpg 16.4 has disp 275.8;
$41111552 has model "AMC Javelin" has gear 3 has wt 3.435 has mpg 15.2 has carb 2 has hp 150 isa automatic-car has cyl 8 has disp 304.0;
$28880 has gear 3 has mpg 10.4 has model "Cadillac Fleetwood" isa automatic-car has cyl 8 has carb 4 has hp 205 has disp 472.0 has wt 5.25;
$282832 has mpg 15.5 has gear 3 has carb 2 has hp 150 has disp 318.0 isa automatic-car has cyl 8 has model "Dodge Challenger" has wt 3.52;
$49256 has mpg 24.4 has carb 2 isa automatic-car has model "Merc 240D" has gear 4 has disp 146.7 has cyl 4 has hp 62 has wt 3.19;
$806984 has gear 3 has disp 120.1 has wt 2.465 has carb 1 isa automatic-car has hp 97 has model "Toyota Corona" has mpg 21.5 has cyl 4;
$340176 has wt 3.84 has disp 350.0 has model "Camaro Z28" has gear 3 has hp 245 isa automatic-car has cyl 8 has carb 4 has mpg 13.3;
$41271320 has gear 3 has carb 2 has disp 360.0 isa automatic-car has cyl 8 has model "Hornet Sportabout" has mpg 18.7 has wt 3.44 has hp 175;
$41291784 has hp 105 has gear 3 has model "Valiant" has mpg 18.1 has carb 1 has disp 225.0 isa automatic-car has wt 3.46 has cyl 6;
$41373848 has gear 3 has mpg 10.4 has hp 215 isa automatic-car has cyl 8 has model "Lincoln Continental" has disp 460.0 has carb 4 has wt 5.424;
$41214040 has model "Merc 280" has hp 123 isa automatic-car has carb 4 has mpg 19.2 has gear 4 has wt 3.44 has disp 167.6 has cyl 6;
$200808 value "Merc 450SE" isa model;
$41340936 value "Fiat 128" isa model;
$41013416 value "Volvo 142E" isa model;
$123088 value "Lotus Europa" isa model;
$164048 value "Fiat X1-9" isa model;
$245832 value "Ford Pantera L" isa model;
$41332904 value "Toyota Corona" isa model;
$196816 isa model value "Mazda RX4 Wag";
$503880 isa model value "Pontiac Firebird";
$86224 value "Maserati Bora" isa model;
$577608 value "Dodge Challenger" isa model;
$847944 value "Chrysler Imperial" isa model;
$450632 isa model value "Mazda RX4";
$86088 isa model value "Cadillac Fleetwood";
$868424 isa model value "Lincoln Continental";
$266448 value "Duster 360" isa model;
$217296 value "Merc 450SL" isa model;
$532552 value "Merc 280" isa model;
$41250968 value "Valiant" isa model;
$41300056 value "Hornet 4 Drive" isa model;
$782408 value "Honda Civic" isa model;
$745544 isa model value "Toyota Corolla";
$20688 value "Merc 450SLC" isa model;
$41267288 value "Camaro Z28" isa model;
$40976536 isa model value "Porsche 914-2";
$41136128 value "Datsun 710" isa model;
$41316360 value "Merc 280C" isa model;
$254056 value "Hornet Sportabout" isa model;
$41017432 value "Ferrari Dino" isa model;
$41050120 isa model value "Merc 240D";
$270408 value "Merc 230" isa model;
$102504 isa model value "AMC Javelin";
$127184 has model "Lotus Europa" has mpg 30.4 has carb 2 isa manual-car has hp 113 has disp 95.1 has wt 1.513 has gear 5 has cyl 4;
$41385984 has gear 3 has wt 3.215 has disp 258.0 has carb 1 isa automatic-car has model "Hornet 4 Drive" has mpg 21.4 has hp 110 has cyl 6;
$561224 has wt 3.57 has gear 3 has model "Duster 360" has hp 245 has disp 360.0 isa automatic-car has cyl 8 has mpg 14.3 has carb 4;
$41050280 has disp 140.8 has wt 3.15 has carb 2 has mpg 22.8 isa automatic-car has model "Merc 230" has gear 4 has cyl 4 has hp 95;
$204904 has model "Merc 450SE" has gear 3 has carb 3 has hp 180 has wt 4.07 isa automatic-car has cyl 8 has mpg 16.4 has disp 275.8;
$41132184 isa manual-car has model "Mazda RX4 Wag" has mpg 21.0 has wt 2.875 has disp 160.0 has carb 4 has gear 4 has hp 110 has cyl 6;
$41132040 has disp 79.0 has wt 1.935 isa manual-car has carb 1 has mpg 27.3 has hp 66 has gear 4 has cyl 4 has model "Fiat X1-9";
$41259096 isa manual-car has carb 1 has model "Fiat 128" has wt 2.2 has disp 78.7 has hp 66 has gear 4 has cyl 4 has mpg 32.4;
$282832 has mpg 15.5 has gear 3 has carb 2 has hp 150 has disp 318.0 isa automatic-car has cyl 8 has model "Dodge Challenger" has wt 3.52;
$49256 has mpg 24.4 has carb 2 isa automatic-car has model "Merc 240D" has gear 4 has disp 146.7 has cyl 4 has hp 62 has wt 3.19;
$12496 has disp 120.3 has hp 91 has carb 2 isa manual-car has mpg 26.0 has wt 2.14 has gear 5 has cyl 4 has model "Porsche 914-2";
$41271320 has gear 3 has carb 2 has disp 360.0 isa automatic-car has cyl 8 has model "Hornet Sportabout" has mpg 18.7 has wt 3.44 has hp 175;
$41013400 has wt 2.77 isa manual-car has carb 6 has mpg 19.7 has disp 145.0 has gear 5 has hp 175 has model "Ferrari Dino" has cyl 6;
$41214040 has model "Merc 280" has hp 123 isa automatic-car has carb 4 has mpg 19.2 has gear 4 has wt 3.44 has disp 167.6 has cyl 6;
$41168984 isa manual-car has mpg 21.0 has model "Mazda RX4" has disp 160.0 has carb 4 has wt 2.62 has gear 4 has hp 110 has cyl 6;
$41353384 has disp 440.0 has gear 3 has hp 230 has mpg 14.7 isa automatic-car has model "Chrysler Imperial" has cyl 8 has carb 4 has wt 5.345;
$159848 has mpg 17.3 has gear 3 has carb 3 has wt 3.73 has hp 180 isa automatic-car has model "Merc 450SL" has cyl 8 has disp 275.8;
$41209856 has disp 400.0 has gear 3 has carb 2 has wt 3.845 isa automatic-car has cyl 8 has mpg 19.2 has hp 175 has model "Pontiac Firebird";
$40964248 has gear 3 has mpg 15.2 has carb 3 has hp 180 isa automatic-car has wt 3.78 has cyl 8 has disp 275.8 has model "Merc 450SLC";
$41250840 has mpg 17.8 has hp 123 has model "Merc 280C" isa automatic-car has carb 4 has gear 4 has wt 3.44 has disp 167.6 has cyl 6;
$41115656 has disp 108.0 has wt 2.32 has model "Datsun 710" isa manual-car has carb 1 has mpg 22.8 has hp 93 has gear 4 has cyl 4;
$41111552 has model "AMC Javelin" has gear 3 has wt 3.435 has mpg 15.2 has carb 2 has hp 150 isa automatic-car has cyl 8 has disp 304.0;
$41369608 has mpg 33.9 has model "Toyota Corolla" has wt 1.835 isa manual-car has carb 1 has hp 65 has disp 71.1 has gear 4 has cyl 4;
$28880 has gear 3 has mpg 10.4 has model "Cadillac Fleetwood" isa automatic-car has cyl 8 has carb 4 has hp 205 has disp 472.0 has wt 5.25;
$41000960 has wt 2.78 has disp 121.0 has carb 2 isa manual-car has gear 4 has hp 109 has model "Volvo 142E" has cyl 4 has mpg 21.4;
$766024 has disp 75.7 has wt 1.615 has mpg 30.4 has hp 52 has carb 2 isa manual-car has model "Honda Civic" has gear 4 has cyl 4;
$41033728 has mpg 15.0 has wt 3.57 has model "Maserati Bora" isa manual-car has disp 301.0 has cyl 8 has gear 5 has hp 335 has carb 8;
$806984 has gear 3 has disp 120.1 has wt 2.465 has carb 1 isa automatic-car has hp 97 has model "Toyota Corona" has mpg 21.5 has cyl 4;
$340176 has wt 3.84 has disp 350.0 has model "Camaro Z28" has gear 3 has hp 245 isa automatic-car has cyl 8 has carb 4 has mpg 13.3;
$41291784 has hp 105 has gear 3 has model "Valiant" has mpg 18.1 has carb 1 has disp 225.0 isa automatic-car has wt 3.46 has cyl 6;
$41373848 has gear 3 has mpg 10.4 has hp 215 isa automatic-car has cyl 8 has model "Lincoln Continental" has disp 460.0 has carb 4 has wt 5.424;
$41058328 has hp 264 isa manual-car has disp 351.0 has mpg 15.8 has cyl 8 has carb 4 has model "Ford Pantera L" has gear 5 has wt 3.17;
$4184 has maker-name "Mercedes-Benz" isa european-maker;
$40964128 has maker-name "Ferrari" isa european-maker;
$16552 isa european-maker has maker-name "Maserati";
$20608 has maker-name "Lotus" isa european-maker;
$49200 has maker-name "Porsche" isa european-maker;
$24664 has maker-name "Fiat" isa european-maker;
$32936 has maker-name "Volvo" isa european-maker;
$290920 isa wt value 1.835;
$41169048 value 4.07 isa wt;
$41230424 isa wt value 3.46;
$40992768 value 5.25 isa wt;
$41078792 isa wt value 3.17;
$41300120 isa wt value 3.84;
$41173000 isa wt value 3.73;
$512072 isa wt value 3.845;
$364616 isa wt value 2.32;
$147528 isa wt value 2.77;
$41136216 isa wt value 1.935;
$307272 isa wt value 3.435;
$41107624 isa wt value 1.513;
$360656 isa wt value 1.615;
$41443328 isa wt value 5.424;
$41296024 value 2.2 isa wt;
$41054216 value 3.57 isa wt;
$16488 isa wt value 2.78;
$41054232 isa wt value 3.15;
$41304232 isa wt value 3.215;
$41320536 isa wt value 5.345;
$241768 isa wt value 3.52;
$40968200 isa wt value 2.14;
$815176 isa wt value 2.465;
$147560 isa wt value 2.875;
$225488 value 2.62 isa wt;
$40980568 isa wt value 3.78;
$41234440 isa wt value 3.44;
$45160 isa wt value 3.19;
$4184 has maker-name "Mercedes-Benz" isa european-maker;
$40964128 has maker-name "Ferrari" isa european-maker;
$37032 has maker-name "Pontiac" isa american-maker;
$41048 isa japanese-maker has maker-name "Honda";
$16552 isa european-maker has maker-name "Maserati";
$8280 isa american-maker has maker-name "Chrysler";
$40968224 has maker-name "Cadillac" isa american-maker;
$24664 has maker-name "Fiat" isa european-maker;
$20648 has maker-name "Chevrolet" isa american-maker;
$28760 isa japanese-maker has maker-name "Toyota";
$20608 has maker-name "Lotus" isa european-maker;
$69680 has maker-name "Ford" isa american-maker;
$49200 has maker-name "Porsche" isa european-maker;
$32936 has maker-name "Volvo" isa european-maker;
$4216 isa japanese-maker has maker-name "Datsun";
$12464 isa japanese-maker has maker-name "Mazda";
$12336 isa american-maker has maker-name "AMC";
$41013336 value 121.0 isa disp;
$41312344 isa disp value 120.1;
$40992920 value 472.0 isa disp;
$69704 value 275.8 isa disp;
$122984 value 95.1 isa disp;
$41046168 value 301.0 isa disp;
$41042088 value 146.7 isa disp;
$299216 value 225.0 isa disp;
$737352 value 71.1 isa disp;
$303176 value 304.0 isa disp;
$41259016 value 360.0 isa disp;
$249928 value 140.8 isa disp;
$94416 value 351.0 isa disp;
$4168 value 120.3 isa disp;
$41287704 value 78.7 isa disp;
$168144 value 79.0 isa disp;
$41132032 isa disp value 108.0;
$41394200 value 460.0 isa disp;
$32872 value 145.0 isa disp;
$192720 value 160.0 isa disp;
$507976 isa disp value 400.0;
$41291944 value 75.7 isa disp;
$41373720 isa disp value 440.0;
$41349120 value 350.0 isa disp;
$229480 value 167.6 isa disp;
$589896 value 318.0 isa disp;
$41316504 value 258.0 isa disp;
$28760 isa japanese-maker has maker-name "Toyota";
$41048 isa japanese-maker has maker-name "Honda";
$4216 isa japanese-maker has maker-name "Datsun";
$12464 isa japanese-maker has maker-name "Mazda";
$24704 value "Lotus" isa maker-name;
$4096 value "Mercedes-Benz" isa maker-name;
$16472 value "Ferrari" isa maker-name;
$4264 value "AMC" isa maker-name;
$28800 value "Mazda" isa maker-name;
$20528 value "Chrysler" isa maker-name;
$24576 isa maker-name value "Porsche";
$28848 value "Honda" isa maker-name;
$20568 value "Chevrolet" isa maker-name;
$20656 value "Toyota" isa maker-name;
$57392 isa maker-name value "Volvo";
$40972320 value "Cadillac" isa maker-name;
$4224 value "Datsun" isa maker-name;
$41080 value "Fiat" isa maker-name;
$40976440 value "Ford" isa maker-name;
$20480 value "Maserati" isa maker-name;
$32944 value "Pontiac" isa maker-name;