match
    $language isa language has name <Language>;
    $country isa country has countrycode <CountryCode>;
insert
    $relation (speaks-language: $country, language-spoken: $language) isa speaks
        has isofficial if(<IsOfficial> = "F") do { false } else { true }
        has percentage <Percentage>;